services:
  mysql:
      image: mysql:8.2
      volumes:
        - ./mysql-init:/docker-entrypoint-initdb.d
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: R00t+
        MYSQL_USER: dashuser
        MYSQL_PASSWORD: dashuser
      healthcheck:
        test: "/usr/bin/mysql --user=root --password=R00t+ --execute \"SHOW DATABASES;\""
        interval: 5s
        timeout: 5s
        retries: 55
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8081" # Forward the exposed port 8081 on the container to port 8081 on the host machine
      # - "5000:5000" # Forward the exposed port 5000 on the container to port 5000 on the host machine
    volumes:
      - "${HOME}/.m2:/root/.m2"
    links:
       - "mysql:mysql"
    environment: # Pass environment variables to the service
      #SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: dashuser
      SPRING_DATASOURCE_PASSWORD: dashuser
      #?useUnicode=true&characterEncoding=utf8&useSSL=false
      #    SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/DashboardAdmin?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&relaxAutoCommit=true
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/DashboardAdmin?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&relaxAutoCommit=true
      #SPRING_PROFILES_ACTIVE: dev,swagger
      SPRING_DATASOURCE_TYPE: com.zaxxer.hikari.HikariDataSource
  web:
    build:
      context: .
      dockerfile: Dockerfile-front
    depends_on:
      mysql:
        condition: service_started
    restart: unless-stopped
    ports:
      - "80:80" # Forward the exposed port 80 on the container to port 80 on the host machine
    volumes:
      - "${HOME}/.m2:/root/.m2"
