services:
  mysql:
      image: mysql:8.2
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: R00t+
        MYSQL_USER: youruser
        MYSQL_PASSWORD: yourpassword
     # copy: ./setup.sql:/docker-entrypoint-initdb.d/
  web:
    build: .
    ports:
      - "8080:8080"
