# Build backend (Spring Boot)
FROM maven:3.9.6-eclipse-temurin-21-alpine as build
VOLUME ~/.m2
WORKDIR /app
COPY backend/pom.xml backend/
COPY backend/src backend/src
WORKDIR /app/backend

# Restore dependencies (utilise le cache Docker si pom.xml n'a pas changé)
# Utilise le cache local Maven pour accélérer les builds suivants
RUN mvn dependency:go-offline -B

# Compile le projet (utilise le cache Maven)
RUN mvn clean package -DskipTests
RUN mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)



#### Stage 2: A minimal docker image with command to run the app
# FROM openjdk:8-jre-alpine
FROM eclipse-temurin:24-noble

ARG DEPENDENCY=/app/backend/target/dependency

# Copy project dependencies from the build stage
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app

# ***************** Test local ***************************************
# mkdir ~/Bureau/Backup/skyapp
# mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)
# sudo cp -r target/dependency/BOOT-INF/lib /app
# sudo cp -r target/dependency/META-INF /app
# sudo cp -r target/dependency/BOOT-INF/classes /app
# cp ~/Bureau/Backup/projet/skyneo/backend/target/api-admin-0.0.8-SNAPSHOT.jar ~/Bureau/Backup/skyapp/
# java -Xms1536m -Xmx1536m -Dspring.profiles.active=dev -jar *.jar com.sos.obs.decc.DashboardAdminApp
# *********** javac -verbose hello.java
# java -verbose -Xms256m -Xmx256m -Dspring.profiles.active=dev -jar *.jar com.sos.obs.decc.DashboardAdminApp
# java -Xms1536m -Xmx1536m -Dspring.profiles.active=dev -cp app:app/lib/* com.sos.obs.decc.DashboardAdminApp

# sudo chmod +r /app/logs/app.log
RUN mkdir /app/logs/
RUN chmod +r /app/logs/

# Run Application
ENTRYPOINT ["java", "-Xms256m", "-Xmx256m", "-Dspring.profiles.active=${ENV_NAME},${ENV_VERSION_NAME}", "-cp", "app:app/lib/*","com.sos.obs.decc.DashboardAdminApp"]

# ENTRYPOINT ["java", "-Xms1536m", "-Xmx1536m", "-XX:+UseConcMarkSweepGC", "-XX:CMSInitiatingOccupancyFraction=70", "-XX:+UseCMSInitiatingOccupancyOnly", "-verbose:gc", "-jar", "/app.jar"]
