# Build backend (Spring Boot)
FROM maven:3.9.6-eclipse-temurin-21-alpine as build-backend
VOLUME ~/.m2
WORKDIR /app
COPY backend/pom.xml backend/
COPY backend/src backend/src
# COPY --from=build-frontend /app/frontend/dist/ ./backend/src/main/resources/static/
WORKDIR /app/backend

# Restore dependencies (utilise le cache Docker si pom.xml n'a pas changé)
# Utilise le cache local Maven pour accélérer les builds suivants
RUN mvn dependency:go-offline -B

# Compile le projet (utilise le cache Maven)
RUN mvn clean package -DskipTests
RUN mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)



# Runtime

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

COPY --from=build-backend /app/backend/target/*.jar app.jar

ARG DEPENDENCY=/app/backend/target/dependency
# Copy project dependencies from the build stage
COPY --from=build-backend ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build-backend ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build-backend ${DEPENDENCY}/BOOT-INF/classes /app



EXPOSE 8081

# ENTRYPOINT ["java", "-jar", "app.jar"]
# Run Application
ENTRYPOINT ["java","-jar","app.jar","com.orange.obs.decc.DashboardAdminApp"]
