# Build frontend (Angular)
FROM node:alpine as build-frontend


WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN rm -rf node_modules package-lock.json
RUN npm version
RUN npm cache clean --force
# sudo sysctl net.ipv6.conf.all.disable_ipv6=1
# export NODE_OPTIONS="--dns-result-order=ipv4first"
# RUN tracepath registry.npmjs.org
RUN npm config set registry https://registry.npmjs.org/
# if you use local registry - https://verdaccio.org/docs/configuration/
# RUN npm config set registry http://localhost:4873/
# RUN npm config set registry http://registry.npmjs.org
# RUN npm set strict-ssl false
RUN npm config list
# RUN npm install bootstrap --loglevel verbose
# RUN npm install react-bootstrap bootstrap
# RUN npm install chalk
# RUN npm install --legacy-peer-deps --offline
RUN npm install --loglevel verbose
RUN npm install @ng-icons/core @ng-icons/heroicons @ng-icons/feather-icons


# RUN npm ci
COPY frontend/ ./
RUN npm run build --prod

# Nginx
FROM nginx:1.12-alpine
# RUN ls /app/frontend/dist

# Copy nginx config
COPY --from=build-frontend /app/frontend/config/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build-frontend /app/frontend/dist /var/www/html

# USER nginx
CMD ["nginx", "-g", "daemon off;"]
